/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.innovatraasolutions.eev.ui;
import com.innovatraasolutions.eev.bo.Parties;
import com.innovatraasolutions.eev.constants.Constants;
import com.innovatraasolutions.eev.controller.Controller;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author SuperMan
 */

public class ManageParties extends javax.swing.JFrame {
  
    
   
    public ManageParties() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        PartyTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        searchtxt = new javax.swing.JTextField();
        ViewallBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        errorMsgLbl = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(680, 540));
        setMinimumSize(new java.awt.Dimension(680, 540));
        setPreferredSize(new java.awt.Dimension(680, 540));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        PartyTable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PartyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name of Party", "Head of Party", "Electoral Symbol"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        PartyTable.setOpaque(false);
        jScrollPane1.setViewportView(PartyTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 190, 660, 180);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setText("Manage Parties ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 10, 180, 40);

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel1.setText("Search Parties:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(410, 60, 210, 30);

        searchtxt.setOpaque(false);
        searchtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtxtActionPerformed(evt);
            }
        });
        getContentPane().add(searchtxt);
        searchtxt.setBounds(410, 90, 210, 30);

        ViewallBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ViewallBtn.setText("View all");
        ViewallBtn.setOpaque(false);
        ViewallBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewallBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ViewallBtn);
        ViewallBtn.setBounds(530, 140, 90, 30);

        searchBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.setOpaque(false);
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchBtn);
        searchBtn.setBounds(410, 140, 90, 30);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        errorMsgLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        errorMsgLbl.setForeground(new java.awt.Color(204, 0, 0));
        errorMsgLbl.setText("No Result Found!");
        jPanel1.add(errorMsgLbl);
        errorMsgLbl.setBounds(160, 80, 230, 60);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("View/Update");
        jButton3.setOpaque(false);
        jPanel1.add(jButton3);
        jButton3.setBounds(50, 420, 140, 40);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Add Parties");
        jButton4.setOpaque(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(460, 420, 140, 40);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Delete");
        jButton5.setOpaque(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(260, 420, 140, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/innovatraasolutions/eev/ui/low_opacity_ecp.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 60, 370, 430);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 660, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

       public Object[] returnObj = null;
    private void searchtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchtxtActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        AddParty addparty = new AddParty();
        this.setVisible(false);
        addparty.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed
                  
    private void ViewallBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewallBtnActionPerformed
          Object[] parameters = new Object[10];
          Controller controller = new Controller();
        try {
            returnObj = controller.processRequest(Constants.ViewAllParty,parameters);
        } catch (SQLException ex) {
            Logger.getLogger(ManageParties.class.getName()).log(Level.SEVERE, null, ex);
        }
          populateTable(PartyTable);
    }//GEN-LAST:event_ViewallBtnActionPerformed

        private void populateTable(JTable table){
            /* adding dummy data: you may have this populated already */
            table.setEnabled(true); /* so that we may select rows */
            
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(new Object[]{"Party Name","Head Of Party","Electoral Symbol"}); /* set headers */
            table.setModel(model);
            
            for(int i=0;i<returnObj.length;i++){
                Parties parties = (Parties)returnObj[i];
              model.addRow(new Object[]{parties.getNameOfParty(),parties.getHeadOfParty(),parties.getElectoralSymbol()});
            }
            
        } 
        
            
            
    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
       Controller controller = new Controller();
       Object[] parameters = new Object[1];
      
       
       parameters[0] = searchtxt.getText();
        try {
            returnObj = controller.processRequest(Constants.SearchParty, parameters);
        } catch (SQLException ex) {
            Logger.getLogger(ManageParties.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       if(returnObj == null)
       {
           errorMsgLbl.setVisible(true);
           //show the error Message here because the returnobj is null
       }
            else 
            {
                populateTable(PartyTable);
            }
       
    }//GEN-LAST:event_searchBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        errorMsgLbl.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DeleteParty deleteparty = new DeleteParty();
        this.setVisible(false);
        deleteparty.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageParties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageParties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageParties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageParties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageParties().setVisible(true);
            }
        });
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable PartyTable;
    private javax.swing.JButton ViewallBtn;
    private javax.swing.JLabel errorMsgLbl;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchtxt;
    // End of variables declaration//GEN-END:variables
}
