/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.innovatraasolutions.eev.ui;

import com.innovatraasolutions.eev.constants.Constants;
import com.innovatraasolutions.eev.controller.Controller;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;

/**
 *
 * @author SuperMan
 */
public class PartyCandidateRegistration extends javax.swing.JFrame {

    /**
     * Creates new form PartyCandidateRegistration
     */
    public PartyCandidateRegistration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AddBtn = new javax.swing.JButton();
        HeadngLbl = new javax.swing.JLabel();
        natxt = new javax.swing.JTextField();
        patxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        otherstxt = new javax.swing.JTextField();
        NoteLbl = new javax.swing.JLabel();
        Fnametxt = new javax.swing.JTextField();
        cnictxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        PartiesBox = new javax.swing.JComboBox();
        picLbl = new javax.swing.JLabel();
        AfdvtLbl = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        errMsgLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        FinishBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 650));
        setMinimumSize(new java.awt.Dimension(900, 650));
        setPreferredSize(new java.awt.Dimension(900, 650));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        AddBtn.setBackground(new java.awt.Color(255, 255, 255));
        AddBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddBtn.setText("Add/Save");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });
        jPanel1.add(AddBtn);
        AddBtn.setBounds(730, 570, 130, 40);

        HeadngLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        HeadngLbl.setText("Enter your Desired Constituencies:");
        jPanel1.add(HeadngLbl);
        HeadngLbl.setBounds(10, 350, 290, 50);

        natxt.setOpaque(false);
        jPanel1.add(natxt);
        natxt.setBounds(140, 400, 180, 30);

        patxt.setOpaque(false);
        jPanel1.add(patxt);
        patxt.setBounds(140, 450, 180, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("If other Specify:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(270, 300, 110, 30);

        otherstxt.setOpaque(false);
        jPanel1.add(otherstxt);
        otherstxt.setBounds(380, 300, 170, 30);

        NoteLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NoteLbl.setText("Please make sure that the information you are giving for the registration is verified and true.");
        jPanel1.add(NoteLbl);
        NoteLbl.setBounds(10, 60, 580, 30);

        Fnametxt.setOpaque(false);
        Fnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnametxtActionPerformed(evt);
            }
        });
        jPanel1.add(Fnametxt);
        Fnametxt.setBounds(90, 150, 180, 30);

        cnictxt.setOpaque(false);
        cnictxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnictxtActionPerformed(evt);
            }
        });
        jPanel1.add(cnictxt);
        cnictxt.setBounds(90, 200, 180, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Incase of any wrong information,The Authorities has the right to disqualify the Candidate according to the Constitution of Pakistan.");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 90, 830, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("*Please Fill the Required Feilds");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 120, 260, 20);

        PartiesBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        PartiesBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PartiesBoxActionPerformed(evt);
            }
        });
        jPanel1.add(PartiesBox);
        PartiesBox.setBounds(100, 300, 160, 30);

        picLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/innovatraasolutions/eev/ui/low_opacity_ecp.jpg"))); // NOI18N
        jPanel1.add(picLbl);
        picLbl.setBounds(250, 90, 360, 350);

        AfdvtLbl.setBackground(new java.awt.Color(204, 204, 255));
        AfdvtLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AfdvtLbl.setText("I hereby confirms that whatever i write the information is true and verified. I will be solely responsible for it if any problem occured");
        AfdvtLbl.setOpaque(false);
        AfdvtLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfdvtLblActionPerformed(evt);
            }
        });
        jPanel1.add(AfdvtLbl);
        AfdvtLbl.setBounds(10, 520, 770, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("National Assembly:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 400, 130, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Provincial Assembly:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 450, 140, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Registration Type:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 260, 130, 30);

        errMsgLbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        errMsgLbl.setForeground(new java.awt.Color(255, 0, 0));
        errMsgLbl.setText("*Please check the Required Feild");
        jPanel1.add(errMsgLbl);
        errMsgLbl.setBounds(20, 500, 760, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CANDIDATE REGISTRATION");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(250, 0, 290, 50);

        FinishBtn.setBackground(new java.awt.Color(255, 255, 255));
        FinishBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FinishBtn.setText("Finish");
        FinishBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinishBtnActionPerformed(evt);
            }
        });
        jPanel1.add(FinishBtn);
        FinishBtn.setBounds(20, 570, 130, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("CNIC:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 200, 70, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Full Name:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 150, 70, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setText("Note:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 40, 40, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Party Name:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 300, 90, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
            Controller controller = new Controller();
            Object[] parameters = new Object[6];
            
            Object[] returnObj = null;
            
                parameters[0] = Fnametxt.getText();
                parameters[1] = cnictxt.getText();
                
                
                parameters[3] = natxt.getText();
                parameters[4] = patxt.getText();
            
            if(!AfdvtLbl.isSelected()){
               
                 errMsgLbl.setVisible(true); 
            }   
            else{
                try {
                    returnObj = controller.processRequest(Constants.AddCandidate, parameters);
                } catch (SQLException ex) {
                    Logger.getLogger(PartyCandidateRegistration.class.getName()).log(Level.SEVERE, null, ex);
                }
               PartyCandidateRegistration partyCandidateRegistration = new PartyCandidateRegistration();
               this.setVisible(false);
               partyCandidateRegistration.setVisible(true);
               
            }
    }//GEN-LAST:event_AddBtnActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        errMsgLbl.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void FinishBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinishBtnActionPerformed
        WelcomeForm Form = new WelcomeForm();
        this.setVisible(false);
        Form.setVisible(true);
    }//GEN-LAST:event_FinishBtnActionPerformed

    private void cnictxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnictxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnictxtActionPerformed

    private void FnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FnametxtActionPerformed

    private void AfdvtLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfdvtLblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AfdvtLblActionPerformed

    private void PartiesBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PartiesBoxActionPerformed
        Connection connection = null;
        try{
           String driverName = "oracle.jdbc.driver.OracleDriver";
           Class.forName(driverName);
           String serverName = "SpiderMan";
           String serverPort = "1521";
           String sid = "XE";
           String dbname = "eev";
           String url = "jdbc:oracle:thin:@" + serverName + ":" + serverPort +  "/" + sid;
           String userName = "eev";
           String password = "123";
           
           connection = DriverManager.getConnection(url, userName, password);
           
           System.out.println("Sucessfully connected to the DataBase");  
       } catch(ClassNotFoundException e){
           System.out.println("Class Not Found Exeption::Couldn't find the database driver" + e.getMessage());
       } catch(SQLException e) {
           System.out.println("Couldn't connect to the database" + e.getMessage());
       }
        /*-----DB connectivity-------*/
        
        try{
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery("select nameofparty from party");
            
            while(resultSet.next()){
                String Nameofparty = resultSet.getString(1);
                PartiesBox.addItem(Nameofparty);
                Object comboitem = PartiesBox.getSelectedItem();
                
                
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_PartiesBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PartyCandidateRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PartyCandidateRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PartyCandidateRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PartyCandidateRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PartyCandidateRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JRadioButton AfdvtLbl;
    private javax.swing.JButton FinishBtn;
    private javax.swing.JTextField Fnametxt;
    private javax.swing.JLabel HeadngLbl;
    private javax.swing.JLabel NoteLbl;
    private javax.swing.JComboBox PartiesBox;
    private javax.swing.JTextField cnictxt;
    private javax.swing.JLabel errMsgLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField natxt;
    private javax.swing.JTextField otherstxt;
    private javax.swing.JTextField patxt;
    private javax.swing.JLabel picLbl;
    // End of variables declaration//GEN-END:variables
}
