/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.innovatraasolutions.eev.ui;
import com.innovatraasolutions.eev.bo.Voters;
import com.innovatraasolutions.eev.controller.Controller;
import com.innovatraasolutions.eev.constants.Constants;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import java.util.List;


/**
 *
 * @author SuperMan
 */
    
    

public class VoterDetails extends javax.swing.JFrame {

    /**
     * Creates new form VoterDetails
     */
    private Voters voterDetail;
    public VoterDetails() {
        initComponents();
    }
    
    public VoterDetails(Voters voters){
        this.voterDetail = voters;
        initComponents();
        populateList();
    }
    
    public void populateList(){
        String cnic = voterDetail.getCnic();
        String Fname = voterDetail.getFname();
        String Lname = voterDetail.getLname();
        String VoteRegistered = voterDetail.getVoteRegistered();
        String Address = voterDetail.getAddress();
        
        cnictxt.setText(cnic);
        Fnametxt.setText(Fname);
        Lnametxt.setText(Lname);
        voteregtxt.setText(VoteRegistered);
        addresstxt.setText(Address);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Fnametxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Lnametxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        voteregtxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        addresstxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cnictxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(685, 475));
        setMinimumSize(new java.awt.Dimension(685, 475));
        setPreferredSize(new java.awt.Dimension(685, 475));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("FirstName:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 180, 70, 30);

        Fnametxt.setOpaque(false);
        jPanel1.add(Fnametxt);
        Fnametxt.setBounds(130, 180, 200, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("LastName:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 240, 80, 30);

        Lnametxt.setOpaque(false);
        jPanel1.add(Lnametxt);
        Lnametxt.setBounds(130, 240, 200, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("VoteRegistered:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 300, 100, 50);

        voteregtxt.setOpaque(false);
        jPanel1.add(voteregtxt);
        voteregtxt.setBounds(130, 310, 200, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Address:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 370, 90, 30);

        addresstxt.setOpaque(false);
        jPanel1.add(addresstxt);
        addresstxt.setBounds(130, 370, 200, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("CNIC:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 130, 80, 30);

        cnictxt.setOpaque(false);
        jPanel1.add(cnictxt);
        cnictxt.setBounds(130, 130, 200, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/innovatraasolutions/eev/ui/low_opacity_ecp.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 0, 540, 470);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Voter's Details");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(170, 10, 260, 40);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/innovatraasolutions/eev/ui/ECPLOGO.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 30, 530, 440);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 680, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VoterDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VoterDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VoterDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VoterDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VoterDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Fnametxt;
    private javax.swing.JTextField Lnametxt;
    private javax.swing.JTextField addresstxt;
    private javax.swing.JTextField cnictxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField voteregtxt;
    // End of variables declaration//GEN-END:variables
}
